### ISSUE TITLE
Erro ao fazer upload das imagens

### ISSUE THREAD

**Issue by jfoza** [robsonvleite/uploader#19]
Olá, quando faço upload tenho este erro.
Att.
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function CoffeeCode\Uploader\exif_read_data() in /home/lupapet/public_html/vendor/coffeecode/uploader/src/Image.php:116
Stack trace:
#0 /home/lupapet/public_html/vendor/coffeecode/uploader/src/Image.php(64): CoffeeCode\Uploader\Image-&gt;checkAngle(Array)
#1 /home/lupapet/public_html/vendor/coffeecode/uploader/src/Image.php(37): CoffeeCode\Uploader\Image-&gt;imageCreate(Array)
#2 /home/lupapet/public_html/AppPets/php/register-company.php(299): CoffeeCode\Uploader\Image-&gt;upload(Array, 'logotipo-de-pet...', 1920)
#3 {main}
  thrown in <b>/home/lupapet/public_html/vendor/coffeecode/uploader/src/Image.php</b> on line <b>116</b><br />

**Comment by jfoza** [comment]
Este erro ocorre somente nos formatos jpeg/jpg, quando utiliza a função $this->checkAngle($image);
